name: Simple Workflow
 
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the file to download'
        required: true
      output_file:
        description: 'Name of the output file'
        required: true
 
jobs:
  simple_job:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Run Python Script
        run: python simple_script.py ${{ github.event.inputs.url }} ${{ github.event.inputs.output_file }}
