name: Read JSON and Fetch Data
 
on:
  workflow_dispatch:
    inputs:
      json_file:
        description: 'Path to the JSON file'
        required: true
      key_to_fetch:
        description: 'Key to fetch from the JSON file'
        required: true
 
jobs:
  build:
    name: Run Python Script
    runs-on: testrun
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Run script
      run: test.py ${{ github.workspace }}/${{ github.event.inputs.json_file }} ${{ github.event.inputs.key_to_fetch }}
